### ISSUE TITLE
Need to scroll to see textboxes 

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#10]
"After installing Pipeline, the textboxes in "Required Information","Options" in the dialog are hidden, so we need to scroll to see it."

cc @rachanasinghg

**Comment by rachanasinghg** [comment]
Hi Marisa,

As required,  a screenshot is attached.
Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
Would you mind attaching the image again? Thanks!

**Comment by rachanasinghg** [comment]
Sending the image again.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
Huh, I'm still not seeing it here or in the other issue, can you email your screenshots to me?

**Comment by marisademeglio** [comment]
Image sent by @rachanasinghg 

![DaisyPipeline_JobShift](https://user-images.githubusercontent.com/734730/206872126-9ae6663d-8fac-46cd-a8b8-a1a15287d6b4.png)

**Comment by marisademeglio** [comment]
@rachanasinghg does this behavior improve if you make the window bigger?

**Comment by rachanasinghg** [comment]
@DeMeglio Marisa ***@***.***>  If I maximize the window,
then the "Required Information" textbox is visible, but "Options" textbox
is still invisible. You need to scroll it to see the textbox.
Is it possible to shift the textboxes to the right-hand side of the
labels?  I mean in the same column of the Run button, as we have a lot of
vacant space on that side and scrolling won't be required.
Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by rachanasinghg** [comment]
@DeMeglio Marisa ***@***.***> no the above screenshot is not
the maximized version on my machine.
I am sending you the maximized window screenshot.Please do have a look.
Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by avneeshsingh** [comment]
It can be fixed after December release if we are running short of time.

**Comment by marisademeglio** [comment]
Fixed by https://github.com/daisy/pipeline-ui/commit/1ee35b8fa5497cf617665b50611e16dd6a80cc48
