### ISSUE TITLE
Drop "INFO" from messages

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#109]
Follow-up of https://github.com/daisy/pipeline-ui/issues/50.

Messages start with the level (INFO, WARNING, ERROR). We could consider dropping it when it is "INFO" to reduce the noise a bit.

**Comment by marisademeglio** [comment]
Here's how it looks

<img width="1474" alt="Screenshot 2023-03-07 at 10 22 33" src="https://user-images.githubusercontent.com/734730/223514819-8f9334e9-7988-4f59-b2c5-1675d9c85ff9.png">

**Comment by bertfrees** [comment]
Some other optimizations possible, but I think it looks better now. You?

**Comment by marisademeglio** [comment]
Yeah it's a little less noisy
