### ISSUE TITLE
rename tray icon "DAISY Pipeline" not "DAISY Pipeline 2"

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#110]

**Comment by marisademeglio** [comment]
Or maybe it should be "DAISY Pipeline - App". We can give it a day for a decision here.

**Comment by ways2read** [comment]
Is the service in the system tray also used by the CLI? If so, I think the service in the tray is "DAISY Pipeline" and the app is the UI.

**Comment by bertfrees** [comment]
Yes, that is the way I see it: the tray represents the background process and has a menu item to configure a job using the graphical UI. You can also connect to the background process (the web server) using the CLI.

**Comment by marisademeglio** [comment]
the tray icon is called "DAISY Pipeline (2023)"
