### ISSUE TITLE
on macOS "Settings…" menu item should have an ellipsis character

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-ui#112]
Just a nitpick: on macOS the usual menu item name would be "Settings…" (with  ellipsis), according to [Apple's human-interface guidelines](https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/the-menu-bar#app-menu).

I'm not sure what's the usual name on Windows. Maybe we can add an ellipsis character on mac only? It's very low priority, but slightly improves the integration in the OS.

**Comment by marisademeglio** [comment]
Windows also seems to use ellipsis although they don't talk about it explicitly in this guide, it shows up in the examples:
https://learn.microsoft.com/en-us/windows/apps/design/controls/menus#create-a-menu-bar
