### ISSUE TITLE
Which entries for help menu

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#117]
In #84, we are talking about what URL to use for the "About" box, and the topic of links used in the Help menu came up. We haven't discussed the Help menu contents as a team, and I realize now that we should. 

Rather than review what's in there now, because it's temporary, we can just say what we want it to look like.

My idea is this on windows:

Help menu:
* "Get help" goes to `daisy.org/pipeline/help` or `daisy.org/pipelineapphelp` or maybe even `daisy.org/pipeline/help/app`
* "About DAISY Pipeline" brings up the about box (which has a subsequent link to the project homepage, see #84 for more discussion of the about box)

And on Mac, the About menu item typically lives under the application menu, so the Help menu would just have one entry, "Get help". 

cc @bertfrees @ways2read @avneeshsingh

**Comment by avneeshsingh** [comment]
For windows:

First item for get help

And second item for about panel/dialog is correct

**Comment by bertfrees** [comment]
I think for now that should be fine.

I'm thinking that we could at some point have a offline help pages integrated in the application, that would exactly match the online documentation.

**Comment by marisademeglio** [comment]
Decision: use `/pipelineapphelp` in the application, have a redirect setup on the server to wherever is appropriate
