### ISSUE TITLE
Results folder name is not user-friendly

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#12]
"Open Pipeline, select any script and run it. When the Result window is shown click the "Show results Folder", Folder gets open but name of the Folder is in Alphanumeric characters, its not at all user friendly."

cc @rachanasinghg

**Comment by marisademeglio** [comment]
Right now, the job results are copied from the pipeline engine's data directory to the user's preferred job results folder, but the UID associated with that job internally (which its folder is named for, e.g. `0fd543f0-9da5-4f47-b6db-ee0af961ba9e`) is still used. 

The Pipeline UI could use the job name plus some extra characters to make the name unique, and use this instead.

**Comment by NPavie** [comment]
For the resolution, for the name of the folder, i am thinking of a timestamped folder name, like `job name (or script name)_YYYY-MM-DD-HHmmss.sss` (not sure about millisecond precision).
@bertfrees @marisademeglio what do you think ? Would this be ok ?

(I was thinking of using the date ISO string format `YYYY-MM-DDTHH:mm:ss.sssZ` but the `:` character is not allowed on windows file name.)

**Comment by bertfrees** [comment]
Sounds like an acceptable solution. (I can't immediately think of a better one.)

**Comment by marisademeglio** [comment]
Fixed by https://github.com/daisy/pipeline-ui/commit/fa0b3583b0e2c7404daedfbf1914f2077e3ea007
