### ISSUE TITLE
Get About box info dynamically

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#120]
Right now it's hardcoded but what should happen is that:

1. The app name and version should come from the app config
2. The engine version comes from a ping to the `/alive` WS endpoint although this now returns no version e.g. `<alive authentication="false" localfs="true" version="???"/>` cc @bertfrees is there supposed to be version info returned?

**Comment by bertfrees** [comment]
Yes

**Comment by bertfrees** [comment]
@marisademeglio The version information is currently stored in a releaseDescriptor.xml file inside the etc folder of the Pipeline engine installation. Currently, in order to find it the `org.daisy.pipeline.home` property (or `PIPELINE2_HOME` env variable) should be set.

**Comment by marisademeglio** [comment]
I'd rather get the version info from the `/alive` endpoint, access to pipeline config files is not guaranteed since we might have a remote pipeline instance someday. I don't mind hardcoding the version info for now.

**Comment by bertfrees** [comment]
`/alive` gets the information from the releaseDescriptor.xml file, but in order to find it it needs the org.daisy.pipeline.home property.
