### ISSUE TITLE
Drop down box is white in dark mode on Windows

### ISSUE THREAD

**Issue by ways2read** [daisy/pipeline-ui#122]
In Windows 11 Settings I set my default app mode to Dark. The Pipeline app is now dark, but the drop-down controls (e.g. Select a script) have a white background. I don't think that's right,

I attach a screenshot of how it looks on my system, and how the settings app has a drop-down list in dark mode.

![image](https://user-images.githubusercontent.com/9092859/225452876-c693468f-9700-4e68-9ac7-9bb4bdaf3e78.png)
![image](https://user-images.githubusercontent.com/9092859/225453762-6280c940-1b84-4c93-95c3-2c7bf0d12df1.png)

**Comment by marisademeglio** [comment]
Interesting, thanks for the report. 

We may double check how we use electron's [nativeTheme module](https://www.electronjs.org/docs/latest/api/native-theme).

Worth noting that macOS, the background of the select element matches the visual theme:

<img width="575" alt="Screenshot 2023-03-16 at 10 23 33" src="https://user-images.githubusercontent.com/734730/225701805-82efcaf9-17ef-44e2-bda2-52fcb28a1f50.png">
<img width="595" alt="Screenshot 2023-03-16 at 10 23 55" src="https://user-images.githubusercontent.com/734730/225701975-5eb2c2fe-8f26-40a7-a4e7-c41d5979396b.png">
