### ISSUE TITLE
While engine is not running it should not be possible to select "New job"

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#123]
The menu item should be greyed out.

**Comment by marisademeglio** [comment]
Yes I can reproduce this. If you are starting the app and the engine is not yet available yet, or if the engine quits while the app is running, the items under the "File" menu are active but they should not be: 

* New job
* Run job
* Status
* Cancel job

The tray menu does the correct thing though, so we do catch engine state changes.
