### ISSUE TITLE
Engine won't start unless previous version is still installed

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#126]
This is on macOS. The current version is 1.0.0-RC2 and the previous version is 1.0.0-RC.

If I delete, rename or move the previous version in the trash the engine won't start (there is no Java process). If the previous version is kept were it is, the current version works. I can also delete the previous version and download and install it at the exact same place and it will work too.

**Comment by rdeltour** [comment]
Oh damn, yes I can confirm. I just deleted the previous version and the engine won't start…

**Comment by rdeltour** [comment]
If I remove the "`pipeline-ui`" directory in "`~/Library/Application Support`" (after I put the 1.0.0-RC app in the trash) , the engine starts correctly.

**Comment by marisademeglio** [comment]
@NPavie can you have a look at this one?

**Comment by bertfrees** [comment]
Yes

**Comment by NPavie** [comment]
@marisademeglio i found the problem.
I was storing and reusing the pipeline and jre pathes from previous install, it works on windows as the package name had not changed so the application install folder remained the same (but its not the case on macos as app are bundled with their displayed name).

I fixed that by removing the use of the settings' path for this (this was a relicate of when i was testing the use of a system-wide pipeline 2 install with the app).

**Comment by NPavie** [comment]
Also, this should fix a side effect i had not come to think of : 
I found out you can launch the app from the DMG, and if i change a setting in this app running from the DMG, it would break the app the same way.

**Comment by bertfrees** [comment]
Fixed
