### ISSUE TITLE
Always show a warning when the application is quit and non-empty jobs are present

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#127]
Especially when the application is quit by closing the window (with the "Close the application" setting active), but also when it quit another way, a warning would be appropriate. The reasoning is that it may always happen that the user quits the application by accident. Most applications will show a warning before quitting if by quitting you will loose data. 

When the "Close the application" setting is combined with "Close all non-running jobs", closing the window already results in warnings, but not when it is combined with "Keep all jobs opened".

**Comment by bertfrees** [comment]
With the version that Marisa sent me last Saturday,  this issue is not fixed yet. Cases where the application still quits without a warning are:

- When an unsubmitted job is present, the "keep running in tray" and "keep all jobs opened" settings are active and the application is quit while the window is not visible.
- When a finished job is present

**Comment by bertfrees** [comment]
I now always get a "Jobs are going to be removed from the application" warning when I quit the application, even if no jobs are present. As a user I wish to not get this warning when it is not needed, e.g. because I already closed all jobs. It is confusing and annoying.

Note that if only finished jobs are present, I would like to get the warning, as is currently the case, but with a "don't warn me again" option, as suggested in https://github.com/daisy/pipeline-ui/issues/128.

**Comment by bertfrees** [comment]
Could this be planned for an upcoming milestone? If it's not too much work, perhaps even the current milestone?

**Comment by NPavie** [comment]
hi @bertfrees , i did a quick round on that : I think i was not correctly filtering the jobs to "protect" from removal so i reworked / rephrased it as this.

If i understand, we want the user to be warned about possibly loosing data in case of jobs that have any data put in it, being either 
- data from a script form being filled (stored as job request data in our structure)
- or data from the pipeline for the job (stored as job data in our structure).

So that the warning should be displayed in presence of any
- Jobs that are under construction
- Jobs that are running
- Jobs that are finished

**Comment by NPavie** [comment]
(for the don't warn me again checkbox, that can be added with an additionnal setting to be specified if its more granular than just "always warn about non empty jobs on closing the application" )

**Comment by bertfrees** [comment]
@NPavie Thanks!

> If i understand, we want the user to be warned about possibly loosing data in case of jobs that have any data put in it

Correct! That was the idea.

Regarding the "don't warn me again" checkbox: I think in addition to not showing a warning when it is not needed (which is really annoying for the user), an option to don't warn again could be useful to because some users will find the warnings annoying anyway.

An additional setting might indeed be useful too. If possible, I think it would be preferrable to combine it with the [two other settings](https://github.com/daisy/pipeline-ui/issues/129).

**Comment by bertfrees** [comment]
@NPavie OK much better, thanks.

**Comment by bertfrees** [comment]
@marisademeglio Yes, can be closed.
