### ISSUE TITLE
Merge the two settings related to window closing

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#129]
The options would be:

- Quit the application
- Keep the application running in the tray and keep all jobs open
- Keep the application running in the tray and close all non-running jobs
- Ask when closing the window

**Comment by NPavie** [comment]
Should the dialog linked to this be changed too to reflect this merge ?

**Comment by bertfrees** [comment]
Yes, I think so. There may be other dialogs too that may unclude (some of the) options. See in this regard also https://github.com/daisy/pipeline-ui/issues/83#issuecomment-1472517701.

**Comment by NPavie** [comment]
I started working on it but it was put in stand by.
it should not take me tool long to update and merge.
