### ISSUE TITLE
Consider letting "Edit job" open a new tab

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#130]
Just an idea.

**Comment by NPavie** [comment]
With how the edit feature is currently implemented, i think it can be quick to do.

The reason i hide it at first was that i liked the idea of staying on the same tab, like if it was actually editing the job i had just run. 
I was also afraid of the possible "many copies" of a job for users who would do edit and rerun a single job a lot of time (to test changing some settings for example).

@marisademeglio and @rdeltour what is your opinion on that ? Do you prefer to keep the original job displayed in a separate tab when clicking on edit ?

(As always, this can also be customized using a setting after choosing for a default behavior 🙂)

**Comment by marisademeglio** [comment]
I think it makes sense to edit it in a new tab by default

**Comment by marisademeglio** [comment]
Works for me

**Comment by bertfrees** [comment]
Works.
