### ISSUE TITLE
Say "quit application" instead of "close application"

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#132]
Nitpick for more consistency: change the phrasing for the "Action on closing the app window" setting. It would be better to say "quit application" instead of "close application" as this is more consistent with how it is called elsewhere (at least on macOS).

> Choose here if you want to keep the application running in the tray or _quit_ it when closing the app window.

> _Quit_ the application

**Comment by marisademeglio** [comment]
Check in with wording again after #129

**Comment by marisademeglio** [comment]
I think we can close this issue now, what do you think @NPavie @bertfrees ?

**Comment by bertfrees** [comment]
Yes, looks fine now!
