### ISSUE TITLE
"Style sheets" option of HTML to braille script does not allow a http URL

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#143]
Not sure whether this is a UI or a framework bug.

**Comment by marisademeglio** [comment]
To me it looks like it's an issue with having a text field with an empty `pattern` attribute which causes the underlying browser engine to apply the `:invalid` pseudoclass. 

Code reference: https://github.com/daisy/pipeline-ui/blob/main/src/renderer/components/Fields/CustomField.tsx#L41

**Comment by bertfrees** [comment]
I have changed the type of the "stylesheet" option in the latest version. See commit https://github.com/daisy/pipeline-modules/commit/99626f8fbc62d9cea8e1ec56aa20a1b54fdd7f24. Perhaps the issue is fixed now? (Note that it has a type ID with a "xs:" prefix now, so we need that other fix to test it.)

**Comment by marisademeglio** [comment]
This seems ok to me now

**Comment by bertfrees** [comment]
Cool

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-ui/pull/144
