### ISSUE TITLE
The select script combo box is not read by Jaws properly

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#15]
"The select script combo box is not read by Jaws properly. When I press down arrow the next script is shown but Jaws says nothing. When I press Alt + Down arrow to open the drop down list and then I press down arrow, Jaws does read out the script name. NVDA is working properly however. Narrator prefixes the field name “select a script” before each script name while navigating the list. For Jaws users this can be an important issue."

@prashantverma2014

**Comment by marisademeglio** [comment]
Ok I am not sure why this would be happening; the markup used for the script selection is in line with basic select element usage. On this page about [testing select box labels with screen readers](https://www.davidmacd.com/blog/select-box-label.html), we are most like their "Test 1", which works ok across screenreaders.

We should see if there are any known electron/JAWS issues, because I don't think it's coming from HTML.

**Comment by prashantverma2014** [comment]
This issue can be closed as it is not happening on other computers I tested on.
