### ISSUE TITLE
If a job request fails, offer to edit the job

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#157]
This would be an enhancement of the current job request error handling, which just reports the error and has a button to close the tab.

There is a state issue with  just invoking the "edit job" function, where the error doesn't get cleared on the server side and the UI reads the job data as if it got an error again.

**Comment by NPavie** [comment]
@marisademeglio i added the functionnality, if you want to test it before closing the issue

(It also helped removing some warning and potential errors reported by my typescript LSP)

**Comment by marisademeglio** [comment]
The app offers to let me edit the job and try again, but when I resubmit the job, it doesn't pick up my changes. Example, in this video I submit a job with an incorrect filepath, but then when I resubmit it with the filepath corrected, it still shows an error:

https://github.com/daisy/pipeline-ui/assets/734730/32fdfc09-e4b0-4e69-8ee1-cfff5c14dbd2

**Comment by NPavie** [comment]
Oups, i forgot to remove the error in the job structure when doing the edit.
Will push the fix

**Comment by marisademeglio** [comment]
Looks good here
