### ISSUE TITLE
Add TTS voice ranking

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#169]
Among the user's preferred voices, they should be able to rank them as high, medium, or low priority.

See https://daisy-dev.slack.com/archives/C064GB8U9/p1700500152643859

**Comment by marisademeglio** [comment]
High = prio 4, Medium = prio 3, Low = prio 2

And derived voices (see #170) get prio 1

**Comment by bertfrees** [comment]
Two levels should be enough, shouldn't it?

**Comment by marisademeglio** [comment]
Yeah true

**Comment by marisademeglio** [comment]
It sounds like, due to #170, we're going to have 2 prio levels: 

- preferred voice
- default voice for language when there is no better preferred match for the language wrt region/gender/age

Is the first one priority "1" and the second priority "2"? Or the opposite? 

From user's point of view, they aren't called "priorities" but rather "preferred" and "default". 

Does all this sound ok?

**Comment by prashantverma2014** [comment]
I think the first one is priority "1" and the second one is priority "2

**Comment by bertfrees** [comment]
@marisademeglio Yes, default voice will need a higher priority so it is chosen over possible other preferred voices.

All sounds OK.
