### ISSUE TITLE
Make file path text field read-only

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#17]
"The edit field before Browse   button can be removed. The user will rarely like to type out the file path. It can be placed after browse button and made read only field with the label “selected file” "

cc @prashantverma2014

**Comment by bertfrees** [comment]
@marisademeglio Perhaps a disadvantage is that it is an extra field that the user needs to tab through?

**Comment by marisademeglio** [comment]
@bertfrees it's a bigger disadvantage to not be able to type in the path directly.

FYI here are some notes about the file/folder picker control design:
https://github.com/daisy/pipeline-ui/wiki/Developer-documentation#about-file-inputs

**Comment by marisademeglio** [comment]
This isn't low-prio as we might not even change anything.

**Comment by marisademeglio** [comment]
Closing with no changes made
