### ISSUE TITLE
Change the tab names

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#18]
"The Tab names should be changed. Currently they read as “1. New job”, “2. New job”, “3. New job”. It can be renamed as “Job 1”, “Job 2” and “Job 3”."

cc @prashantverma2014

**Comment by marisademeglio** [comment]
This is a little tricky; right now the tabs are numbered to correspond with the visual tab order, not any default job name.

So I would not change that aspect of the job name but I think elsewhere there is a request to change the job name as soon as the user picks a script from the drop down.

**Comment by avneeshsingh** [comment]
It is not a high priority for December release. We can discuss it further after upcoming release.

**Comment by marisademeglio** [comment]
In the latest commit ( https://github.com/daisy/pipeline-ui/commit/0e57c9932fd75d64c24f914c2107f072498152f4 )

* the job is called "Untitled job" until a script has been selected
* the job name changes when a script is selected
* the jobs are numbered according to position in the tab list
