### ISSUE TITLE
Too many warning messages that aren't meaningful or actionable

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#189]
Recent tester feedback:

"The user experience could be improved by not displaying the many warning messages that are not meaningful or actionable by the typical user."

**Comment by marisademeglio** [comment]
I agree, it would be nice to streamline any user-facing messages.  @ways2read did you have specific things that stood out to you?

**Comment by marisademeglio** [comment]
Info from a call: this issue is about the script messages, not dialog boxes that might pop up. Request to simplify presentation in the UI. 

Also -- when dealing with all these messages appearing constantly, the screenreader gets overwhelmed and keeps speaking and users don't get important updates like that the job has finished. 

Ideas:
* collapse entire messages section
* just show warnings
* turn off aria-live for the messages 
* show warnings and show last info statement per nesting level

**Comment by marisademeglio** [comment]
Decided on the team chat to do this one in addition to removing `aria-live` (already done): "show warnings and show last info statement per nesting level"

**Comment by marisademeglio** [comment]
The commit above does what we said above ("show warnings and show last info statement per nesting level") except it doesn't show the warnings out of context.  The approach taken here is to show the most recent message per nested level except when there is a warning. In that case, the ancestor messages of the warning are also shown.

The other option is to get rid of the nesting and show the warnings out of context. This would result in fewer messages remaining in the UI messages view at the end of the job.

@bertfrees want to have a look and let me know what you think? I would post a screenshot but it's more meaningful "live" e.g. when running a job.

**Comment by marisademeglio** [comment]
Discussed https://daisy-dev.slack.com/archives/C064GB8U9/p1719593846632609

**Comment by marisademeglio** [comment]
Description for the latest commit here:

Turning verbosity on automatically turns warnings on.

Errors are shown regardless.

In non-verbose mode, the outer two levels of messages are shown in a flat list.

In verbose mode, all messages are shown in a hierarchy.

How this looks in practice depends on the script. DTBook to braille looks good; DAISY 202 to EPUB 3 does not have nested messages so verbosity control does little here.

**Comment by marisademeglio** [comment]
Scripts vary in their messages - some report nested messages, some report a lot of things, some report very little. So the idea of "verbose" is hard to define relative to this.

After trying a few approaches, I think the most consistent and easiest is if we show errors and warnings by default, and then show everything if the user chooses.

This is what's available in the test build here:  https://github.com/daisy/pipeline-ui/actions/runs/9726989779

**Comment by bertfrees** [comment]
> I think the most consistent and easiest is if we show errors and warnings by default, and then show everything if the user chooses.

I think this solution is fine. Let's see what the users say.
