### ISSUE TITLE
Change title of "create new job" button

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#19]
"The “+” button for creating a new tab is read by screen reader as “create new job tab”. It can be “Add new tab button”"

cc @prashantverma2014

**Comment by marisademeglio** [comment]
So far I cannot quite reproduce this; specifically the word "new" does not appear for me. When I inspect the document accessibility tree, the name of the "+" button is "Create job". And I guess the screen reader adds "tab" to that. So we could call it "add new job", which the screenreader will turn into "add new job tab"? I don't want to call it "add new" just to get it to say "add new tab", because that's a bad description by itself (add new what? there will be some other features coming that could also have components called "add new <something>", so I want to be specific from the start)

**Comment by prashantverma2014** [comment]
I agree with changing it to "add new job",

**Comment by bertfrees** [comment]
I would skip the "add". It's not better than "create" IMO (on the contrary). Just "New job" sounds perfect. And it's still fine if the screen reader adds "tab" to it. I can't check right now what the corresponding menu items are called, but I'd expect them to be called the same as the + button.

**Comment by marisademeglio** [comment]
Ok so is "new job" (proposed wording) better than "create job" (existing wording)? I don't really see the difference. 

The menu item is called "create a job" but that may undergo some changes too (see #7).

**Comment by prashantverma2014** [comment]
New job is closer to the terminology used in most apps including  some DAISY apps such as new project, new file, new folder etc.

**Comment by bertfrees** [comment]
Indeed I was thinking the same. There isn't much difference between the two, but "new" is more common.

**Comment by marisademeglio** [comment]
I am going to hold off on this until we sort out tab naming, because if we rename the "add job" button to "new job", then it has the same name as the default tab name, so you could have a tab list where everything is called "new job". 

See #26 and #18

**Comment by avneeshsingh** [comment]
I face a different issue here. JAWS does not say that it is a button.
JAWS correctly says its name "Create job ctrl+N tab"
But JAWS does not recognize it as a button. Please check if it has role button assigned to it.

**Comment by marisademeglio** [comment]
@avneeshsingh it's a tab:

```
<button role="tab" type="button">
```

I am still looking for a good accessible example of HTML tabs that contain controls. I sent an email about this last week which I did not receive replies to so I will create an issue and maybe get some discussion going. The problem is that something with role="tab" cannot contain interactive elements like buttons.

**Comment by marisademeglio** [comment]
I have removed the "new job" button in favor of a menu item (and keyboard shortcut) in commit https://github.com/daisy/pipeline-ui/commit/0e57c9932fd75d64c24f914c2107f072498152f4
