### ISSUE TITLE
TTS should optionally process alt text too

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#193]
From recent tester feedback:

"When adding TTS in a conversion, offer the option to include the alt text (like we see with some readloud experiences)."

**Comment by bertfrees** [comment]
@marisademeglio Shall I transfer this issue to the pipeline-modules repo?

**Comment by marisademeglio** [comment]
Has this been transferred and can we close it here?

**Comment by bertfrees** [comment]
Is this a duplicate of https://github.com/daisy/pipeline-modules/issues/84?
