### ISSUE TITLE
Override document language tags

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#195]
From recent tester feedback:

"Word to DTBook xml to DAISY 3 with TTS audio is our prefered work flow. Most time wrong language tags are  added in DTBook xml. Thus almost all books do not get created in right language and voice. Users have to manually open DTBook xml to correct language tags for any book to get recorded. Let Pipeline app over-ride language tag of DTBook xml until the Save As DAISY issue on this is resolved."

**Comment by marisademeglio** [comment]
Also mentioned:

"Pipeline app ignores chosen language and voice

DTBook language tag is given preference over chosen language in Pipeline app. We should have a choice to give preference to the language chosen in Pipeline app."

**Comment by bertfrees** [comment]
This sounds like a Save-as-DAISY issue (based on the first comment).

It is not clear to me what is meant by this comment:

> DTBook language tag is given preference over chosen language in Pipeline app.

What is the "chosen language in Pipeline app"?

**Comment by prashantverma2014** [comment]
I think it means that in Pipeline App > Settings we choose TTS voice of a particular language but that voice is not used. 

If Pipeline app  detects some other language in the XML then it picks a voice on its own.

**Comment by NPavie** [comment]
Fixed in SaveAsDAISY with installer 2.8.4 that has been sent to test at the end of February.

I'm closing the issue here (issue in SaD remains open while waiting for testers feedbacks)
