### ISSUE TITLE
Unable to deselect a voice

### ISSUE THREAD

**Issue by ways2read** [daisy/pipeline-ui#196]
To replicate:

- open the Pipeline app
- Navigate through File menu, Settings, Voices
- Helpfully at the bottom of the list there information about the currently selected voices (e.g. "3 selected: en-GB-BellaNeural, pl-PL-MarekNeural, AvaMultilingualNeural")
- Use the handy Search feature to identify one of these voices. If it is not checked, then it is not possible to deselect this (as in the attached screenshot)

Perhaps this is an artifact of having used earlier pre-release builds?

![image](https://github.com/daisy/pipeline-ui/assets/9092859/ce468814-65e7-499a-9d31-68564ea28e4d)

**Comment by ways2read** [comment]
In `settings.json` I have:
```
        "preferredVoices": [
            {
                "name": "en-GB-BellaNeural",
                "gender": "female-adult",
                "lang": "en-GB",
                "engine": "azure",
                "id": "azure-en-GB-BellaNeural",
                "show": false
            },
            {
                "name": "pl-PL-MarekNeural",
                "gender": "male-adult",
                "lang": "pl-PL",
                "engine": "azure",
                "id": "azure-pl-PL-MarekNeural",
                "show": true
            }
        ],
        "ttsEngineProperties": [
            {
                "key": "org.daisy.pipeline.tts.azure.key",
                "value": "15401cdb21a14ee397199f303ea8211a"
            },
            {
                "key": "org.daisy.pipeline.tts.azure.region",
                "value": "westeurope"
            }

```
And in case you are interested in `ttsConfig.xml` I have:

```
<config>
<voice engine="azure" name="en-GB-BellaNeural" lang="en-GB" gender="female-adult" priority="1"/>
<voice engine="azure" name="pl-PL-MarekNeural" lang="pl-PL" gender="male-adult" priority="1"/>
<property key="org.daisy.pipeline.tts.azure.key" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
<property key="org.daisy.pipeline.tts.azure.region" value="westeurope"/>
</config>

```

**Comment by marisademeglio** [comment]
This was resolved by removing `settings.json` and letting it be recreated. We can reopen if it comes up again.

**Comment by ways2read** [comment]
I am afraid that the issue of a selected / not selected voice has re-emerged on my computer.

App version: 1.2.7-RC1, 
        Engine version: 1.14.16, 
        Engine is running  on 127.0.0.1:49152/ws
        
![image](https://github.com/daisy/pipeline-ui/assets/9092859/28fe567d-0779-4930-a3c3-1690e831ea23)

**Comment by marisademeglio** [comment]
@ways2read does this happen with the latest release? https://github.com/daisy/pipeline-ui/releases/tag/1.2.7

**Comment by marisademeglio** [comment]
This is no longer relevant with the new TTS voices selection dialog
