### ISSUE TITLE
Close tab button title needs to include name of job that it will close

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#20]
"When more than one tab has been opened, pressing the tab key moves the focus to “X” (close” button of other tabs  and Jaws reads it as “close tab job new button”. The label should include the name of tab that will be closed.   "

cc @prashantverma2014

**Comment by prashantverma2014** [comment]
I think these issues can be fixed if the name of the script selected becomes the tab name.

**Comment by marisademeglio** [comment]
Yes I agree, I have been thinking along similar lines. We may also consider letting users create their own names for jobs, it's already supported on the Pipeline backend.

**Comment by bertfrees** [comment]
I wanted to test this issue but I don't seem to have a close button anymore. There is also no menu item to close jobs. Is this expected?

**Comment by bertfrees** [comment]
Never mind, I missed the button is at the bottom ^^.
