### ISSUE TITLE
Error messages are not user-friendly

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#204]
We received this feedback 

1. On running a Job only by selecting a job with empty textboxes, we get a message "Required jobRequest input port arg(s) missing: source," it should be more user friendly.

2. On entering a wrong input in Textbox, press Run button, we get a message "Input not found: a relative path was specified but no context provided". There is only a Close job button, nothing to go back and edit the input in the textbox.

**Comment by marisademeglio** [comment]
In these cases, the error messages come from the engine and are displayed as-is by the UI

**Comment by bertfrees** [comment]
It sounds like this might be related to https://github.com/daisy/pipeline-ui/issues/30 (job form validation), rather than the engine. Are some of the inputs marked `required` in the web API? It would be good to know which text boxes they are talking about exactly.

**Comment by marisademeglio** [comment]
Need to invoke form validation when Ctrl+R is pressed, instead of submitting the job to the engine

**Comment by marisademeglio** [comment]
We should probably switch to custom validation that is invoked a deeper level than HTML form validation, and use it everywhere.

**Comment by marisademeglio** [comment]
Closing this as it will be handled in #218
