### ISSUE TITLE
Tab navigation improvements

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#21]
"I strongly feel that the multiple jobs feature can be done away with in first version. If not, the tab navigation needs to be improved. A “run all job” button is also essential as the user will not find it convenient to go to each tab to start the process. Can Ctrl + Tab be assigned for tab navigation?  "

cc @prashantverma2014

**Comment by bertfrees** [comment]
> A “run all job” button is also essential as the user will not find it convenient to go to each tab to start the process.

I'm not sure I understand why such a button is essential. In a normal workflow, the user will fill out a job form and then submit it. The most common use case will then be that the user waits for the job to finish. The other use case is that the user will go on submitting more jobs forms while other jobs are still running, so it is indeed important that he can navigate between jobs. But I don't see such a benefit in being able to submit several jobs at once. 

> I strongly feel that the multiple jobs feature can be done away with in first version.

Personally I also think it might have been better to have no tab interface initially, but provide a way to have multiple windows (one for each job). This way navigation between jobs would have been a OS native thing.

I'm all for the tab interface if it works well though.

Ideal would be a combination of tabs and multiple windows, I think, like in browsers. That would give the user the flexibility to arrange and navigate jobs the way he prefers.

**Comment by prashantverma2014** [comment]
I was told that users may like to leave the system running as they go out of office with jobs that take time i.e. those using TTS.

IN such a case, they can add several jobs and then start them all together.

Starting such jobs and also creating new jobs in parallel may make the system slow, or users may have that apprehension.

The other Pipeline   has run all jobs option.

**Comment by marisademeglio** [comment]
This issue has been split into 3 issues so I am closing it here but please continue the discussions.
