### ISSUE TITLE
Results links not working on Mac

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#216]
The results folder link and the individual results links launch a finder window when clicked on but it goes to the home folder, not the correct location.

**Comment by marisademeglio** [comment]
I find that if I move the Pipeline results folder out of Documents, I can open the paths in finder. E.g. `/Users/marisa/dev/DAISY Pipeline results/...` is ok whereas `/Users/marisa/Documents/DAISY Pipeline results/...` does not work. Suspect something changed either with my local permissions or with macOS.

`drwx---rwx@  28 marisa  staff       896 Feb 20 19:03 Documents`

`drwxr-xr-x   79 marisa  staff      2528 Apr 15 17:15 dev`

Setting g+r, g+x on Documents does nothing useful. 

Documents has an extended attribute "macl" which apparently entered the macOS universe sometime around Ventura. This might be the issue? 

``` 
> xattr -l Documents
com.apple.macl:
```

One thing we could do is suggest users to move their Pipeline results out of the Documents folder, and/or create a new default location.

**Comment by marisademeglio** [comment]
I tried to make `Desktop` like `Documents` but could not reproduce the behavior.

```
drwx---rwx@  36 marisa  staff      1152 Apr 16 11:58 Desktop
drwx---rwx@  28 marisa  staff       896 Feb 20 19:03 Documents
```

And `Desktop` also has the same extended attribute as `Documents`:
```
❯ xattr -l Desktop
com.apple.macl:
```

So maybe that's not the reason.

**Comment by marisademeglio** [comment]
@bertfrees what macOS version are you on?

**Comment by marisademeglio** [comment]
I am on Sonoma 14.2.1 (23C71)

**Comment by bertfrees** [comment]
Sonoma 14.0

**Comment by marisademeglio** [comment]
Ok it must just be something with my machine; will close this but keep an eye out for user reports in case we have to reopen.
