### ISSUE TITLE
Make "job status" an <h2>

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#22]
"The “Job status” should also be given `<h2>` tag as “Settings and Messages for easier navigation to it."

cc @prashantverma2014

**Comment by marisademeglio** [comment]
So if it's a heading 2, then a screen reader will read it when you ask for the list of headings? Is there an even faster way?

**Comment by avneeshsingh** [comment]
It will be helpful to assign H2 to status.
It is a long page, and headings help screen reader users to quickly focus on relevant information.
It is not a critical issue, but since it is small change, it can be done soon.

**Comment by marisademeglio** [comment]
Is this preferable to having something like a keyboard shortcut that always reports the status? 

If so, to preserve document semantics, I would restructure it as this (right now it's all in one "p" element):
```
<h2>Job status</h2>
<p aria-live="polite">Completed (100%)</p>
```

But does that defeat the purpose of using an h2 if the user still has to read past it to get the status value? I don't want to put the status value inside the h2, because then we have an h2 with nothing that comes after it, which may also confuse users.

**Comment by avneeshsingh** [comment]
We can try aria live here, along with a keyboard shortcut.
