### ISSUE TITLE
indicate whether script uses TTS in its name/description

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#225]
@prashantverma2014 can tell us more about what wording will be good here.

Technically we can tell which scripts use TTS by seeing which ones have an input of type `application/vnd.pipeline.tts-config+xml` so those can automatically get the indication appended to the name or description.

**Comment by prashantverma2014** [comment]
Suggested changes of description of some of the scripts: 

DTBook to DAISY 3
This script converts DTBook (XML file) to DAISY 3 format. Text can be recorded in TTS voice.  

DTBook to EPUB 3
This script converts dtbook (XML file)  to EPUB 3 format. Text can be recorded in TTS voice.

EPUB 3 Enhancer
This script transforms an EPUB 3 publication into an EPUB 3 publication with audio and/or a braille rendition. Text can be recorded in TTS voice.

EPUB to DAISY
This script transforms an EPUB 2 or EPUB 3 publication into DAISY 2.02 and DAISY 3. Text can be recorded in TTS voice.

**Comment by marisademeglio** [comment]
Ok so nothing like "(TTS enabled)" in the short name (which appears in the dropdown)?

**Comment by prashantverma2014** [comment]
TTS enabled is a great suggestion. I could not think of a short phrase and hence focussed on the description.

You may include (TTS enabled) and the description also.

**Comment by marisademeglio** [comment]
We should be able to do it easily in the GUI

**Comment by bertfrees** [comment]
OK great.
