### ISSUE TITLE
Make job submission a two-step process for more scripts

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#227]
Make job submission a two-step process for all scripts that have both a "stylesheet" and a "stylesheet-parameters" option. In addition to the [braille scripts that already have a two-step job submission process](https://github.com/daisy/pipeline-ui/issues/198), dtbook-to-daisy3, dtbook-to-epub3, epub3-to-epub3, epub-to-daisy and zedai-to-epub3 will soon also be such scripts.

The `<media>` element should be "embossed" for PEF output, "speech" for scripts with TTS enabled. dtbook-to-daisy3, dtbook-to-epub3 and zedai-to-epub3 have an "audio" option to enable or disable TTS. When TTS is disabled, the `/stylesheet-parameters` call should not be made. The epub3-to-epub3 script has both braille and speech support. It has a "tts" option to enable/disable TTS (I might rename this to "audio") and a "braille" option to enable/disable braille translation. The `<media>` element should contain "braille" (not "embossed"), "speech" or "braille, speech" (or no `/stylesheet-parameters` call should be made) depending on which of the options are set. epub-to-daisy also has a "tts" option which I might rename to "audio".

The following is actually a separate enhancement, but I will mention it here:

There will soon also be support for an additional element in the `/stylesheet-parameters` request document, namely`<userAgentStylesheet>`, with a `mediaType` attribute that should correspond to the input of the script:

- `<userAgentStylesheet mediaType="application/x-dtbook+xml"/>` for dtbook-to-pef, dtbook-to-daisy3 and dtbook-to-epub3
- `<userAgentStylesheet mediaType="application/xhtml+xml"/>` for html-to-pef, epub3-to-pef, epub3-to-epub3 and epub-to-daisy
- `<userAgentStylesheet mediaType="application/z3998-auth+xml"/>` for zedai-to-epub3

**Comment by marisademeglio** [comment]
Noting that the feature described above would allow alt text to be read by TTS

**Comment by NPavie** [comment]
@bert just to be sure about the evaluation of the mediatype :
will the mediatype in question be deductible from the scripts' endpoints when the stylesheet endpoint is updated ?

Right now, if i take the script "epub-to-daisy", I have 2 mediatype exposed in the code for the script source input when building the request : 
`mediaType: [ 'application/epub+zip', 'application/oebps-package+xml' ],`
I don't have the `application/xhtml+xml` you mentioned.

(the quickest solution I think of is to store a map of script and stylesheet targeted media type to be used when building the request to the stylesheet endpoint)

**Comment by bertfrees** [comment]
I would go for a map of script name to media type for now. I currently don't have a way to pass on that information. Same for the output medium.

**Comment by marisademeglio** [comment]
This is now working for me with the dtbook-to-daisy3 script reporting a "Speak image alt" option in its 2nd step.

**Comment by marisademeglio** [comment]
Here is a test build: https://github.com/daisy/pipeline-ui/actions/runs/9880197849

**Comment by bertfrees** [comment]
Works, but I noticed a small issue: the "Speak image alt text" option is not shown conditionally on whether the "Enable text-to-speech" option is set in the first step.

Not such a big deal, but I think I saw some code in a588f77a9272d1 to handle this, which means that code doesn't work.

The other scripts have the same issue.
