### ISSUE TITLE
Settings dialog, TTS voices page: display names of TTS engines

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#228]
@bertfrees [commented](https://github.com/daisy/pipeline-ui/issues/170#issuecomment-2147207769)
> In the voices dialog, you capitalize the engine name. Engines also have a "display name". I will make that available in the web API.

Is there a (pipeline) engine issue for this that we can monitor?

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-modules/issues/94

**Comment by bertfrees** [comment]
Note that https://github.com/daisy/pipeline-modules/issues/94 is done, but I'm not sure if the changes are included in the engine snapshot that you are currently using in the GUI. I think they are.

**Comment by marisademeglio** [comment]
Yes it's already there but the names need to be shorter. 

```
<tts-engines href="http://localhost:49152/ws/tts-engines">
    <tts-engine name="osx-speech" nicename="macOS" status="available" voices="http://localhost:49152/ws/voices?engine=osx-speech"/>
    <tts-engine message="Property not set: org.daisy.pipeline.tts.google.apikey" name="google" nicename="Google Cloud" status="disabled"/>
    <tts-engine features="speech-rate" name="azure" nicename="Microsoft Azure" status="available" voices="http://localhost:49152/ws/voices?engine=azure"/>
</tts-engines>
```

**Comment by bertfrees** [comment]
Yes, names have been made shorter also but that part has not end up in the snapshot yet.

**Comment by marisademeglio** [comment]
Ok, well the UI change has been incorporated, it'll use whatever the engine provides. I think we can close this one.
