### ISSUE TITLE
"Completed" status with many errors in the messages view

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#234]
Testing feedback from @rachanasinghg for 1.4.0-beta

>  the status says as "Complete" but in the result window you can see there are lots of errors.

![DP_FalseCompleteReport](https://github.com/daisy/pipeline-ui/assets/734730/2f9c8eb0-41d8-4c91-b8dd-39a3c5c45b69)

Can you email me the DAISY 2.02 book that you used for this job? I can't reproduce it with the ones I have handy at the moment.

**Comment by rachanasinghg** [comment]
I have mailed you the Daisy 2.02 book. Thanks.

**Comment by marisademeglio** [comment]
ok I ran this job with the "light man" book and I didn't get any of the same errors. The job completed and it made an EPUB. @bertfrees any thoughts? I can send you the book if you need it.

**Comment by bertfrees** [comment]
I've seen it before [here](https://github.com/daisy/pipeline-modules/issues/77) but wasn't able to reproduce either, also not on Windows.

It is not a fatal error, that is why the job completes. But the doctype might not be set in the output.
