### ISSUE TITLE
Any changes required for support of TTS voice-family

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#237]
This may not have an impact on the UI but keep an eye on it:
https://daisy-dev.slack.com/archives/C064GB8U9/p1719242760816719

**Comment by marisademeglio** [comment]
So far, there are no changes expected in UI related to voice-family. This issue may get closed or moved. 

https://daisy-dev.slack.com/archives/C064GB8U9/p1723476887384829?thread_ts=1723476120.081709&cid=C064GB8U9

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-modules/issues/92. As Marisa said, no changes expected.
