### ISSUE TITLE
job progress not displayed correctly

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#239]
Versus the CLI which shows it correctly based on what the web service is reporting. 
@bertfrees can you add any more details here? Are you seeing job progress in the UI just not finely-grained enough? As in, it goes from 0-100 with nothing in between? Or it's not shown at all? 

It may be a display issue or it could be related to the web service polling interval.

**Comment by bertfrees** [comment]
The progress goes from not being displayed at all to "Progress: **100%**" when the status changes to "Status: **Completed**".

**Comment by marisademeglio** [comment]
Ok what's a good script to test this with?

**Comment by marisademeglio** [comment]
This fix is in the test build: https://github.com/daisy/pipeline-ui/actions/runs/9726989779

**Comment by bertfrees** [comment]
Seems to be fixed.
