### ISSUE TITLE
include sponsorship message

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#245]
Show a message on first run and then every few weeks. On build, refresh the message from the DAISY-provided link.

https://daisy-dev.slack.com/archives/C064GB8U9/p1723477812834739

**Comment by marisademeglio** [comment]
This has been added but there is a CORS issue with fetching the sponsorship message at runtime; this can be addressed in a future version. For now, the message is hard-coded and matches the latest available at the time of coding.

**Comment by bertfrees** [comment]
@NPavie had the idea of showing the message through a system notification, and is going to try it for Save-as-DAISY. I think it will be a very nice and non-obtrusive solution, if it can be done. We think it would also work for the GUI.

**Comment by marisademeglio** [comment]
Oh well I've already implemented it in the Pipeline GUI

**Comment by NPavie** [comment]
I have not checked back how effective and customizable are the notification with electron yet (i did some tests a while back for jobs notification but i'm not sure i kept the code, from memory if was easy enough if we want to look at it at some point)

In the meantime, I assume It might be a bit too much and could be close to spamming to include both types of sponsorship requests 😄

**Comment by bertfrees** [comment]
Yes, we probably don't want both. The notification could be an improvement over the current solution. But let's first test both approaches.

**Comment by marisademeglio** [comment]
Let's chat about it the next time we meet. I feel like what's in there now is minimum viable and could be good enough. With this release coming up soon, our development time will be busy with other things.

**Comment by bertfrees** [comment]
This was done.
