### ISSUE TITLE
Users should have a fast way to edit and re-run a recent job.

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#28]

**Comment by marisademeglio** [comment]
I don't think this will be a v1 feature so can we even say what priority it might have?

**Comment by bertfrees** [comment]
I thought Nico was working on this feature?

**Comment by marisademeglio** [comment]
Oh really? @NPavie is this true?

**Comment by NPavie** [comment]
hum i think this is a good idea but i don't remember saying I was working on it (if is said so, I had not the time to assess the issue)
Before the issues review, I was working on keeping job states in the backend to recover them on re-opening a window (that could be part of #32)

**Comment by bertfrees** [comment]
Oh, misunderstood then. 

> keeping job states in the backend to recover them on re-opening a window

Would we use that feature though? Or is it more about making the code more robust and preparing for the future?

Remember that currently we've left persistence out of the picture completely, to simplify things for both the users and the developers. When a job tab is closed, it is discarded and can't be brought back.

The design document describes how we could do persistence, but the way I think about that now is that's it's for a faraway future.

**Comment by marisademeglio** [comment]
@bertfrees no both this issue and #32 are different than Pipeline-side persistence. 

This issue came from a notepad of ideas that I had. We have not yet evaluated it as a feature or assigned it to anyone, nor have we scheduled it as part of any release.

**Comment by bertfrees** [comment]
In my last comment I wasn't talking about this issue (#28) or #32 but about what Nico said ("keeping job states in the backend to recover them on re-opening a window"). To me this sounds like a kind of persistence. When I say persistence I'm not talking about Pipeline-side persistence but also about e.g. closing a job tab and then bringing it back. To me what Nico said sounded like that: "recover on re-opening a window". Maybe I've just misunderstood again.

**Comment by marisademeglio** [comment]
the new features work for me :)
