### ISSUE TITLE
Store state on backend

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#32]
Right now, web service calls and the global list of Pipeline jobs are part of the renderer code (see MainView). I think this should all be moved to the main process instead to reduce our dependency on React and give us more flexibility. 

Redux could be a good choice.

**Comment by NPavie** [comment]
@marisademeglio i managed to get the webservice status check working on the backend !
For now and to avoid repetitive webservice calls that quickly expand the pipeline logs, i remove the alive call when the webservice launch is confirmed.

I put it on a fix-32 branch, and i also put the initial code i made to have scripts and jobs state stored in the backend.

I would also like to initialize scripts list on the backend while I'm at it, but i will need to replace the DOMParser (by using something like jsdom) on the renderer side when porting the parsing code to backend.

In the end, i might remove the "alive" call for webservice status check by directly trying the scripts request and consider the webservice available when i have the list of available scripts.

i'll link the branch to the issue.

**Comment by marisademeglio** [comment]
That's great!  Glad it's working now. 

I would like us to chat about this refactor as it's pretty significant. Probably the next thing to do is setup Redux and start making commands and other structures. Then we can use your fetching code to fill in the logic.

**Comment by marisademeglio** [comment]
Issues that could be positively impacted if this issue were completed (basically anything related to UI commands like tab navigation, job creation, etc): 

https://github.com/daisy/pipeline-ui/issues/35
https://github.com/daisy/pipeline-ui/issues/14
https://github.com/daisy/pipeline-ui/issues/52
https://github.com/daisy/pipeline-ui/issues/51
https://github.com/daisy/pipeline-ui/issues/39
