### ISSUE TITLE
Job data should be deleted

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#36]
When a job tab [or the whole window](https://github.com/daisy/pipeline-ui/issues/83) is closed, or the application is quit, the corresponding job on the server should be deleted. The consequence will be that the job data within the engine is deleted (to be clear this is within ~/Library/Application Support/pipeline-ui/jobs on macOS, not within ~/Documents). It is important to free up the disk space when possible because the job data can take up a lot of space.

Just in case, the job data folder could be pruned at startup (in case the application was force-quit).

**Comment by marisademeglio** [comment]
Agree on both points

**Comment by bertfrees** [comment]
@NPavie Are you not using the API to delete jobs?

**Comment by bertfrees** [comment]
The job data is not deleted when the job is closed. Presumably it is done only at shutdown (haven't checked this yet). It would be better to actually delete the job through the API.
- When we add persistence we will have to delete jobs through the API anyway.
- The same is true for when we will support connecting to external server in the future.
- When the engine is running for a very long time, freeing memory only on shutdown is not optimal.
