### ISSUE TITLE
Tabs vs windows

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#37]
From [#21 ](https://github.com/daisy/pipeline-ui/issues/21#issuecomment-1346455604)

**Comment by marisademeglio** [comment]
cc @bertfrees

**Comment by marisademeglio** [comment]
I don't think this is low-priority yet, I'm not even sure we should do it.

**Comment by marisademeglio** [comment]
Closing this as it's not really an issue (what would it solve?)

**Comment by bertfrees** [comment]
I still have this on my list of possible improvements. It's fine to close the issue if we don't have concrete plans to do it yet. It's not high priority. It also doesn't really solve an issue. But I do think it could be an improvement. I compare it with a browser, where you have the choice, or can have a combination, between windows and tabs. OK, running Pipeline jobs is not quite te same as a browsing the web, but still. Users have a choice. There can be all kinds of reasons why they prefer one or the other. Maybe they are more comfortable navigating OS windows than navigating within the application. Maybe they want to see two job windows side by side. Maybe they want to group a number of jobs in one window.
