### ISSUE TITLE
Ctrl + Tab for tab navigation

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#39]
From #21 

cc @prashantverma2014

**Comment by marisademeglio** [comment]
Implemented in https://github.com/daisy/pipeline-ui/commit/0e57c9932fd75d64c24f914c2107f072498152f4

**Comment by NPavie** [comment]
@marisademeglio i tested your changes regarding navigation with nvda and keyboard navigation : 
The tab change/selection is working, but nvda is not reporting the new selected tab : the keyboard focus remains on the tab button that was originally focused with the keyboard and nothing is pronounced.

I have found an example of accessible tabs with keyboard navigation that I found interesting here and is working well with nvda : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role

I can replace direct tab selection by keyboard focus navigation with Ctrl + (Tab | Shift + Tab) to move the keyboard focus and get it to work with nvda (to be tested with jaws, i don't know if jaws also prioritize focus change announcement or if it is more talkative).

**Comment by NPavie** [comment]
Ok it is almost a oneliner to fix : just adding the following the MainView seems sufficient to get the tab focused and announced by nvda : 
```js
useEffect(() => {
        document.getElementById(`${ID(pipeline.selectedJobId)}-tab`).focus()
    }, [pipeline.selectedJobId])
```
I'll push the fix now
