### ISSUE TITLE
Rename Hide and Quit menu items

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#40]
In the "DAISY Pipeline" menu:
- "Hide pipeline-ui (⌘H)" should become "Hide DAISY Pipeline (⌘H)"
- "Quit pipeline-ui (⌘Q)" should become "Quit DAISY Pipeline (⌘Q)"

**Comment by marisademeglio** [comment]
Are you trying this on macOS ? We have to adjust the distributable package to name the app menu correctly, it's one of the weird things about Electron. See [main menus on macOS](https://www.electronjs.org/docs/latest/api/menu#main-menus-name).

**Comment by bertfrees** [comment]
Yes, forgot to mention, all my testing has been on macOS.
