### ISSUE TITLE
Close window when sole tab is closed

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#41]
Currently, when you close the sole job tab, a new "New job" tab is created, even if the tab that was closed was already a "New job" tab, and sometimes after a delay of a few seconds. I think it would be more intuitive if the whole window would be closed if the last tab is closed.

Some other solutions could be:

1. Depending on whether the tab is a "New job" tab or not, close the window or open a "New job" tab.
2. Show an empty window (with only the "+" button) if the last tab is closed.

**Comment by marisademeglio** [comment]
I don't really agree here, I think it's ok how it is. What's the point of an empty window with only a "+" button?

**Comment by bertfrees** [comment]
> What's the point of an empty window with only a "+" button?

It's a compromise. I was just thinking maybe this would be better for accessibility than to close the window. Because if the window is closed, the app is also not on the foreground anymore, and not in the list of the application switcher either (⌘-Tab key on macOS), so the tray menu must be used to get the application back on the foreground, and perhaps that is less preferable accessibility-wise.

There are several solutions possible to my issue. I basically just want to prevent that the user tries to close a tab (he is challenged by the close button to do so) but that the app doesn't let him.

Admittedly, this is nit-picking. I gave it the low priority label. But it's one of those small things that could be done to optimize the user experience.

**Comment by marisademeglio** [comment]
Ok I think it's not quite low-priority yet as we still need to discuss exactly what behavior we want to have.

**Comment by marisademeglio** [comment]
Right, you would just close the window instead. I think the adjustment here would be to not use a tabbed view when there's only one job open.

**Comment by bertfrees** [comment]
Hmm yes I think that could be a nice adjustment. Indeed some other applications do that.

**Comment by NPavie** [comment]
Currently, when only one "empty" tab remains, trying to close the tab actually close the window (similarly as what browsers do).
The slight difference with browsers is that if the last tab is not "empty", it does not close the window but instead it recreates an empty the job tab, for users who would want to close the job before relaunching a new one (and closing this last empty tab then closes the window).

If this intermediate empty job creation is problematic, I can deactivate this when closing the last non-empty job tab. 
(And it does indeed not follow the more common tabs-based UX that users are used to, like most chrome based browsers or firefox, that makes sense)

For the tabbed view removal, what we could do to minimize work on this, and as to keep the + button visible to let user create new jobs from the UI, is to simply not render the job tabs list if only one job is present (not sure how much accessible this would be though)

**Comment by NPavie** [comment]
nevermind I think i'm tired, i though i add make change it but i was using the wrong action, i might have stash that without pushing it ><
i'll fix that asap

**Comment by bertfrees** [comment]
For completeness sake I'll document the new behavior when the user cancels the last job tab:

- when it is not an empty job, the tab is replaced by an empty job tab
- when it is an empty job, the tab is closed, resulting in a window without tabs, after which the "The application can keep running in the tray" prompt comes up
  - "Cancel" results in a new empty job tab
  - "Stop the application" or "Keep the application in tray" close the window
