### ISSUE TITLE
"Choice" type of options should be presented in radio button list or dropdown list

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#45]

**Comment by marisademeglio** [comment]
Can you link to the documentation for what these script options look like in the XML returned by the web service? Then we can better support them in the future.

**Comment by bertfrees** [comment]
Can you do something with a schema file?

**Comment by bertfrees** [comment]
Web service API needs quite a bit of work. I don't know where to start and don't have enough time this month. 

I think the existing documentation about the [`/datatypes` API](http://daisy.github.io/pipeline/WebServiceAPI/#data-types) together with this [schema file](https://github.com/daisy/pipeline-framework/tree/master/framework-core/src/main/resources/org/daisy/pipeline/datatypes/resources) should be sufficient for now. The following relevant code of the CLI could also be of help:
- https://github.com/daisy/pipeline-clientlib-go/blob/aad11eb63a/pipeline.go#L250
- https://github.com/daisy/pipeline-cli-go/blob/15490da660/cli/scripts.go#L298
- https://github.com/daisy/pipeline-cli-go/blob/15490da660/cli/scripts.go#L354
- https://github.com/daisy/pipeline-cli-go/blob/15490da660/cli/scripts.go#L498

I'm inclined to label this mid priority because it's quite important for the UX.

The CLI uses the datatype info both for option validation and for documentation. E.g. the 

```
```

The GUI currently does not have

**Comment by marisademeglio** [comment]
Ok thanks, it may take longer to implement this way but I agree that it would be good to have.
