### ISSUE TITLE
`null` is passed as option value in certain cases

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#47]
An example is the "stylesheet-parameters" option in the "DTBook to braille" script (when left empty). This option is defined in XProc as follows:

```xml
<p:option name="stylesheet-parameters"
          required="false"
          px:type="transform-query"
          select="''">
```

Another example is the "template" option in the "DTBook to ODT" script (when left empty). This option is defined in XProc as follows:

```xml
<p:option name="template"
          required="false"
          px:type="anyFileURI"
          select="''"
          px:media-type="application/vnd.oasis.opendocument.text-template">
```

Perhaps it's the `required="false"` in combination with the `select=""`?

**Comment by marisademeglio** [comment]
Well the UI just gets its script info from the web service, it doesn't parse the XProc files at all. What does the web service return for these scripts?

**Comment by bertfrees** [comment]
Yeah I know. In the web service API it looks like this:

```xml
<option default=""
        desc="OpenOffice template file (.ott) that contains the style definitions. [...]"
        mediaType="application/vnd.oasis.opendocument.text-template"
        name="template"
        nicename="Template"
        ordered="true"
	required="false"
        sequence="false"
        type="anyFileURI"/>
```
