### ISSUE TITLE
Option descriptions that contain inline `<code>` look weird

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#49]
Look e.g. at the "Metadata" option of the "EPUB 3 Enhancer" script.

**Comment by marisademeglio** [comment]
Oh yeah looks like the CSS for the rest of the app is getting applied to the option descriptions, which have been transformed from markdown to display as HTML (with some special handling to open links in the browser instead of the app window).

**Comment by bertfrees** [comment]
Mid priority because it's quite disturbing and probably not so hard to fix.

**Comment by marisademeglio** [comment]
I don't notice this anymore but @bertfrees can you check with the upcoming release?

**Comment by bertfrees** [comment]
It's fixed.
