### ISSUE TITLE
Improve rendering of messages

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#50]

**Comment by marisademeglio** [comment]
Can you be more specific? 

In the meantime maybe you'll find an answer here:

https://github.com/daisy/pipeline-ui/blob/main/src/renderer/pipelineXmlConverter/jobToJson.ts#L89

https://github.com/daisy/pipeline-ui/blob/main/src/renderer/components/JobDetailsPane/Messages.tsx

If there are issues with the message conversion from web service XML to JSON, I think the answer is probably for the WS to provide the "official" JSON conversion.

**Comment by bertfrees** [comment]
Yeah, a pointer to the code was what I was after :-)

Basically the messages didn't look like I expected, and for a minute I thought it was maybe implemented some other way then by parsing the job XML from the web API. Hence my question.

I think I wouldn't include the time stamps. They mostly just distract IMO.

The other thing that could be improved is that the nesting of messages is currently not manifested in the UI.

**Comment by marisademeglio** [comment]
styles need updating in dark mode but i can take care of it when i fine-tune the CSS (and address #68 )
<img width="1066" alt="Screenshot 2023-02-09 at 10 04 47" src="https://user-images.githubusercontent.com/734730/217899952-90943a77-5f67-40ad-86e4-5255548bf101.png">
<img width="1039" alt="Screenshot 2023-02-09 at 10 05 03" src="https://user-images.githubusercontent.com/734730/217899969-898bfc38-b1a5-4f71-83f4-64257f450149.png">

**Comment by marisademeglio** [comment]
style updated in https://github.com/daisy/pipeline-ui/commit/cf8036ec0146c6b236a25d5551b1c00126bf645c
