### ISSUE TITLE
JAWS does not recognize "new job" button as a button

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#51]
"I face a different issue here. JAWS does not say that it is a button.
JAWS correctly says its name "Create job ctrl+N tab"
But JAWS does not recognize it as a button. Please check if it has role button assigned to it."

_Originally posted by @avneeshsingh in https://github.com/daisy/pipeline-ui/issues/19#issuecomment-1347797794_

**Comment by marisademeglio** [comment]
@avneeshsingh it's a tab:

```
<button role="tab" type="button">
```

I am still looking for a good accessible example of HTML tabs that contain controls. I sent an email about this last week which I did not receive replies to so I will create an issue and maybe get some discussion going (see #52). The problem is that something with role="tab" cannot contain interactive elements like buttons.

**Comment by prashantverma2014** [comment]
Jaws is not identifying "New job" as a button. It is reported as "tab".

**Comment by marisademeglio** [comment]
This shouldn't be an issue any longer since I removed that button in favor of a simple menu item / keyboard shortcut
