### ISSUE TITLE
Tab accessibility question

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#52]
When I was designing the tab components, I was curious about how tabs with a “close tab” button are best done regarding accessibility. No one includes these in web accessibility examples so while I followed those for basic tab properties and interactions,I decided on putting two buttons side by side for each tab, one for ’activate tab’ and the other for ‘close tab'. Does this work though, in practice? 

See also #51 

cc @avneeshsingh @prashantverma2014

**Comment by avneeshsingh** [comment]
The main question is, do we want user to perceive it as tab or as a button. JAWS reads out the following.
 1. New job alt+1 tab
Close tab   New job button
Create job ctrl+n tab


I need to do hit and trial to discover which control is doing what.
The 2nd row is very confusing.

First thing is labels exposed to screen reader users. And then comes information about actionable controls.
One way can be try placing aria labels on these tabs.
I would also suggest you to try it wout with voiceover or NVDA. It would make it more clear.

**Comment by marisademeglio** [comment]
Are there any good examples of sites with accessible tabs that contain a "close" button? That's what I'm after. 

Tabs are interactive controls, and as such, they cannot contain other interactive controls (e.g. buttons). So I am wondering how this sort of thing gets implemented, if ever.

**Comment by avneeshsingh** [comment]
Usually screen reader users use shortcut key ctrl+F4 on windows to close the tabs. I have not seen a explicit button to do so.
