### ISSUE TITLE
Don't provide a link for every file in "Results" box

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#53]
from https://github.com/daisy/pipeline-ui/issues/44#issuecomment-1351843258:

> When I suggested to have buttons/links for all results, I meant results as in "direct children of the `results` element". [...] The child `result` elements are the individual files within each result. [...] I don't think it makes that much sense to include them.

**Comment by bertfrees** [comment]
I think it would be better to not list the individual files at all. Not the links, but also not the file names.

**Comment by NPavie** [comment]
If I recall, the files list was a request from initial tester feedbacks.
(I agree it would be better though IMO)

**Comment by bertfrees** [comment]
Imagine what it looks like when the output contains an audio book with tons of MP3 and SMIL files. Why would you want to see that in the UI? Perhaps it would be acceptable when collapsible. Do you remember what was the motivation?
