### ISSUE TITLE
Move "log" link to messages area, not results

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#55]

**Comment by marisademeglio** [comment]
From #42 (@bertfrees )

It would be more appropriate to put the "Log" link in the "Messages" box, or in the vicinity of it. It's more related to messages than to results.

**Comment by bertfrees** [comment]
There are now 2 links to the log: "Log" under Results and "View log" under Messages. I guess this was an oversight?

Also, a better name for the link (under Messages) would be something like "View _full_ log" or "View _detailed_ log", to make clear that it is not the same as the log that is shown in the UI.

**Comment by bertfrees** [comment]
Reopening the issue as the link was not really moved (the old one is still there).
