### ISSUE TITLE
"Create new job" doesn't do anything

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#7]
"Open Daisy Pipeline,select any script and run it. When the script is running open File menu, press Create new Job , nothing will happen."

cc @rachanasinghg

**Comment by marisademeglio** [comment]
My experience is that if the Pipeline is minimized, for example, and you choose "create new job" from the tray menu or the file menu, then the Pipeline window is shown. But if you're already looking at the Pipeline, then it doesn't do anything.

I think we should change either the name of the menu item or the function. 

@NPavie what do you think? Should we attach this menu item to a command that creates a new job tab? Or rename it "show pipeline"?

**Comment by bertfrees** [comment]
I strongly suggest we attach this menu item to a command that creates a new job tab. It makes perfect sense to have a "New job" menu item in addition to the "+" button, it just needs to do what it says.

If the main window is closed (not just "hidden" with ⌘-H on macOS), it means all jobs and job forms have been discarded, so currently it does not really make sense to have a "Show jobs window". "New job" would do exactly what we need, namely open the main window with a single "New job" tab.

**Comment by marisademeglio** [comment]
There is not yet a command to map this to but I am seriously considering doing #32 because it would give us some global commands that I think will also help with keyboard shortcuts and other menu items. So maybe we can both work on #32 and then everything will just fall into place?

**Comment by bertfrees** [comment]
I'm personally in favor of not deferring refactorings too long. Have you got an idea of how much work it would be?

It sounds like this is mostly needed for some mid priority issues though, not the high priority ones. Am I right?

**Comment by marisademeglio** [comment]
@bertfrees Are you talking about this issue or #32?

**Comment by bertfrees** [comment]
#32

**Comment by marisademeglio** [comment]
File -> New job creates a new job tab as of this commit https://github.com/daisy/pipeline-ui/commit/0e57c9932fd75d64c24f914c2107f072498152f4
