### ISSUE TITLE
Warn the user about the app running in the tray

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline-ui#74]
Follow up from #58:

On closing the application main window, we might need to warn the user that the app remains launched in the tray.

On closing the window for the first time, we could ask the user if the application needs to remain open on closing the window and save its preference in settings.

**Comment by NPavie** [comment]
Other proposition : 
On first launching the application, we could warn the user that the app is also running in the tray and will remain in the tray when closing the main window.

**Comment by ways2read** [comment]
Also, if the app is launched and is already running in the tray, the window should be restored.

**Comment by bertfrees** [comment]
> Also, if the app is launched and is already running in the tray, the window should be restored.

Apparently, at least on macOS, this is already the behavior!

**Comment by NPavie** [comment]
I though it was working but there was a minor thing to add for windows for this behavior to work (i though it was but i probably tested it on macos last time).
Now it should be good for restoring/refocusing the main application window when trying to relaunch the app.

**Comment by bertfrees** [comment]
Works well. Just a minor thing: "DAISY pipeline" is written with a small "p".

**Comment by bertfrees** [comment]
I found another issue: it's documented [here](https://github.com/daisy/pipeline-ui/issues/96).
