### ISSUE TITLE
Provide a way to close a new job tab when the script has not been chosen yet

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#79]
A finished job has a "Delete" button, a job form has a "Cancel" button when the script has been chosen. For consistency I suggest adding the same "Cancel" button when the job has not been chosen yet?

**Comment by NPavie** [comment]
Already fixed in 395ccf73a46801601990893d5c538ab012698396

**Comment by bertfrees** [comment]
OK this is fixed. It's not possible to close the tab when it is the last tab in the window though (https://github.com/daisy/pipeline-ui/issues/41).
