### ISSUE TITLE
Hidden window appears again as soon as tray icon is clicked

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#82]
I think it would be more logical if the window would appear only upon opening a new job form. The point of the tray icon is exactly to decouple the user interface for jobs from the background process / server. It should be possible to manage the server by only using the tray menu and settings window.

**Comment by NPavie** [comment]
> I think it would be more logical if the window would appear only upon opening a new job form.

I don't see this behavior as an issue: 
As a regular MS Windows user, I'm used to being able to open back an application from the tray (for example, most Microsoft applications like teams or outlook let this possibility to the user).

It is merely another possibility for users to open back the application main window, as widely found in Windows applications with tray access.

**Comment by NPavie** [comment]
Given that, I propose to remove the click behavior as default, except for user who would want to keep the job opened when the window is closed (in which scenario it would be interesting).

**Comment by bertfrees** [comment]
Ok. I'm not sure these two things (close behavior and tray icon click behavior) are really related though. So perhaps two separate settings are better.

Have you got an idea about the "glitchy" behavior I described above?

**Comment by NPavie** [comment]
> Say if I want to use the tray menu to open the settings panel, which in the future might have settings to start/stop the server and configure it

As it has been requested that we don't touch/use the configuration files of the pipeline, the configuration aspect will need webservice API endoitpoint(s).

> Have you got an idea about the "glitchy" behavior I described above

For the expected behavior, I can remove completely the click to open the window for macOS if it is the conventional behavior for this platform.
(I did not think it was opening the contextual menu on left-clicking a tray icon on macOS, my bad)
I'll keep it for windows to maintain the OS conventions if it is ok.

**Comment by bertfrees** [comment]
> As it has been requested that we don't touch/use the configuration files of the pipeline, the configuration aspect will need webservice API endoitpoint(s).

Configuration of the Pipeline engine would only be possible for the embedded engine. The feature wouldn't be available when connecting to an external server. The configuration settings would be passed when launching it, with Java system property arguments or environment variables. With a "properties" file is possible too (I don't remember saying it can not be used), although I think it makes much more sense to use environment variables or Java arguments. A webservice endpoint to configure the engine does not make that much sense to me. It does not sound like a good idea from a security point of view, and in general just sounds unneeded.

> I can remove completely the click to open the window for macOS if it is the conventional behavior for this platform. [...] I'll keep it for windows to maintain the OS conventions if it is ok.

This sounds like a good default. But in addition a setting could also be useful I think. (We can keep the latter for some next iteration though.)

**Comment by bertfrees** [comment]
> I'm not sure these two things (close behavior and tray icon click behavior) are really related though. So perhaps two separate settings are better.

On second thought, it does indeed make sense to have a single setting for both the close behavior and the tray icon click behavior (which is how it is currently done). My bad. The alternative is to keep the application in the dock and the ⌘-tab list when the window is closed and allow re-opening the window this way.
