### ISSUE TITLE
Make Job’s name read only

### ISSUE THREAD

**Issue by prashantverma2014** [daisy/pipeline-ui#89]
The new “Job’s name” is a edit field. It should be made read-only. And its label could be “selected Job”.
At present the user may have a confusion what is expected in this field. And if the user deletes the “Job’s name” text, the tab name changes.

**Comment by NPavie** [comment]
Hi Prashant, thanks for the feedback

The idea between this field is to let user "customize" the jobs name (as permitted by the pipeline by giving a "nice name" to it).

Would it be acceptable if we either rename the field or add a description to better explain what it's use is ?
(I added it a bit quickly without adding much details to it)

**Comment by prashantverma2014** [comment]
You may rename it. How about naming it "custom job tab name" and keeping it blank. At this time the Job tab name will be same as selected script name. When user will input something in this edit field, the job tab name will change.
