### ISSUE TITLE
On macOS, move "Settings" menu item under "DAISY Pipeline app"

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#95]
On macOS the "Settings (⌘,)" or "Preferences (⌘,)" menu item is usually placed in the menu with the name of the application. Almost always the name "Preferences" is chosen.

**Comment by bertfrees** [comment]
Yes, on Mac I always see "Preference," never "Settings". I checked:

- Firefox
- Slack
- Emacs
- iTerm
- Eclipse
- Acrobat Reader
- Numbers
- Books

**Comment by marisademeglio** [comment]
Ah this is why 
https://www.macworld.com/article/803390/macos-ventura-system-preferences-settings.html

**Comment by bertfrees** [comment]
I suspected it would be something like that.

**Comment by marisademeglio** [comment]
Ok so can we stick with "Settings", since I think that is good for Windows too?

**Comment by bertfrees** [comment]
I guess so. I liked "Preferences" better but consistency is more important.
